// Canonical skills dataset for the entire hub. Dashboard counts, the Skills
// tracker, the Claude catalog, downloads, and the Cowork bundle all derive
// from this module. Update this file first; do not create a second registry.
export const SKILLS_AUDIT_DATE = "2026-07-13";

export type SkillTier = "live" | "hold" | "retired" | "vendor" | "frozen" | "restricted" | "command" | "other";
export interface SkillRow {
  num: string; section: string; id: string; folder: string;
  forr: string; when: string; how: string; get: string;
  status: string; tier: SkillTier; flow: boolean;
}
export const skillRows: SkillRow[] = [
  { num: "WR 1", section: "WR", id: "wr.beats", folder: "story-beats", forr: "Turning an idea or a winning reference ad into the locked skeleton of a story ad before any real writing happens.", when: "Start of a new story ad. You say \"beat this out\" / \"story beats for this idea\" or hand me a reference script to adapt.", how: "I ask what the reference/idea is, then produce a beat sheet. The 6-part arc (hook, context, issue, lander-solution, payoff, CTA) is the FLOOR, not a ceiling — convoluted stories expand to 8-10+ beats (multi-POV, parallel lines, misdirection, bigger ensembles). Must-hit dialogue anchors marked (mechanism line, ticking clock, emotional hinges). Compliance-checked against floors + PFM rules. You approve/edit the skeleton; connective dialogue comes later in the script pass.", get: "A beat sheet in chat — the approved skeleton that wr.script builds on.", status: "Team", tier: "live", flow: false },
  { num: "WR 2", section: "WR", id: "wr.aiscript", folder: "veo-script-writing", forr: "Writing or fixing scripts destined for AI video, where every line becomes one 8-second generated clip and bad formatting breaks the voice.", when: "Drafting a new Veo script, rebalancing an existing one (\"these lines are too long\"), or a pre-fire compliance check.", how: "Applies the locked line rules: 17-25 words per 8s line, no dashes/ellipses/ALL-CAPS, contractions kept, numbers routed through wr.numbers, SMA disclaimer gate if the brand needs it. Numbered lines map 1:1 to clips so the manifest and QC can key on them.", get: "A numbered, fire-ready script (in chat and/or pushed to the Notion request).", status: "Team", tier: "live", flow: false },
  { num: "WR 3", section: "WR", id: "wr.humanize", folder: "human-ad-copy", forr: "Stripping the AI-tells out of written ad copy so long-copy and headlines read like a person wrote them.", when: "LAST pass on any written copy deliverable — after the content is right but before it ships.", how: "Runs a scanner over the text for tell patterns (em-dash cadence, tricolons, hedge words), then rewrites flagged spots using 15 proven frameworks. Compliance rules always win over style suggestions.", get: "The cleaned copy plus a note of what changed.", status: "Team", tier: "live", flow: false },
  { num: "WR 4", section: "WR", id: "wr.numbers", folder: "naturalize-numbers", forr: "Making dollar amounts sound human when spoken by AI voices — the single owner of the spoken-number rules.", when: "Any script with dollar figures, before firing. \"Naturalize the numbers\" — or wr.script routes here automatically.", how: "Runs naturalize.py with the locked high/low logic: big yearly rates round to clean reads ($4,164 → \"forty two hundred\"), low monthlies read as pairs ($391 → \"three ninety one\"), savings floor to 50s. Shows you before/after per line; VSL slides are exempt (opposite rule — they spell full thousands).", get: "The script with spoken-read substitutions, ready for the manifest.", status: "Team", tier: "live", flow: false },
  { num: "WR 5", section: "WR", id: "wr.suno", folder: "suno-songwriter", forr: "Writing the Suno lyrics + style block when an ad becomes a song (state music videos, jingles). PFM does all its music in Suno, so this is the Suno songwriter.", when: "\"Turn this into a song\" / any Suno work. Auto-assumes when a script + music intent show up together.", how: "Drafts V1 lyrics from the script's beats, critiques itself, delivers V2 — locked rules: no em dashes in lyrics, style block under 1,000 chars. Genre is picked PER creative (I pitch 2-3 if you're open) — country ballad, americana stomp, indie pop, kids singalong, trap, etc. — no single default. YOU run Suno by hand (take-gen + pick); I prep everything.", get: "Paste-ready lyrics + style block.", status: "Team", tier: "live", flow: false },
  { num: "WR 6", section: "WR", id: "wr.pod.lc", folder: "lc-to-video-podcast", forr: "Converting a winning Facebook long-copy ad into a podcast-monologue script — the highest-volume creative conversion at PFM (200+ requests).", when: "A \"LC to Video\" Notion request, or you paste long-copy and say \"make this a podcast\".", how: "Transforms written-ad voice into spoken podcast voice (the craft), chops it into numbered 6-8s lines per wr.aiscript's rules, runs numbers through wr.numbers, adds the compliance scan + SMA gate, then pushes the script to the Notion request and OFFERS the gen handoff — a yes chains straight into ag.stage (whose own preflight + Fire? gates still run), a no ends cleanly at the script.", get: "A Veo-numbered podcast script on the request, ready to stage/fire.", status: "Team", tier: "live", flow: false },
  { num: "WR 7", section: "WR", id: "wr.bn", folder: "breaking-news-story-ads", forr: "Writing story ads wrapped as a local 6pm news segment (LATU News) — anchor grammar, reporter packages, chyron text.", when: "Any \"breaking news\" creative — fresh script or converting an existing story ad into the news wrapper.", how: "Applies the news-segment grammar (anchor intro → field package → interviews → anchor close) with the locked broadcast-voice rules and compliance floors; the 2:00 template + cliché guards live in reference files. Graphics are NOT written here — ag.bn.thirds/ag.graphics.call own strips and banners.", get: "The news-wrapped script; on-screen text specs for the graphics skills.", status: "Team", tier: "live", flow: false },
  { num: "WR 8", section: "WR", id: "wr.batches", folder: "notion-state-batches", forr: "Scaling a proven creative to all 50 states by writing the follow-on Notion requests (not the videos).", when: "After Batch 1 ships and you say \"make batches 2-6\" / \"scale to all 50\".", how: "Reads Batch 1, applies the locked cadence (B2-B4 = 10 states, B5 = 5, B6 = 10 Final), builds each request with per-state toggles and fills, handles a/an grammar and duplicate-state dedup, fires batches sequentially so links resolve, then re-fetches to verify 50-state coverage.", get: "Batches 2-6 live on the VTM, verified complete.", status: "Team", tier: "live", flow: false },
  { num: "WR 9", section: "WR", id: "wr.request", folder: "wr.request", forr: "Turning a brief into a fully spec'd Notion request — the enforcement surface so requests are BORN in the locked format instead of freehand.", when: "\"Write a request\" / \"make a Notion request\" / \"spec this request\" / handing me a brief that should become a request.", how: "Pulls what it can from the brief (asks only the gaps), sets the spec properties (blank = default), applies the display-name title grammar, and builds the locked body itself — spec table atop Instructions + the four callouts + one static numbered script. For a variant it wires the Parent Creative relation + a REUSE/NEW map + a 2-column delta-script. It is the SOLE format surface — no Notion template needed; it rebuilds the whole body every time so nothing can drift or break.", get: "A correctly-spec'd request live on the VTM that fires without a clarifying round.", status: "Team", tier: "live", flow: false },
  { num: "WR 10", section: "WR", id: "wr.cutoff", folder: "wr.cutoff", forr: "Writing a CUT-OFF / interrupted Veo line so the TTS cuts clean — the one sanctioned exception to the no-dash dialogue law. Josiah Akimenko's technique, maintained by him.", when: "The script calls for someone being cut off, stopping mid-word, or having their sentence finished by another speaker — \"she gets interrupted here\", \"he can't say the word\", \"wr.cutoff\". Opt-in, per beat.", how: "Ends the fragment with an em-dash exactly at the cut point (\"With the—\") — never a ? or ellipsis, which make Veo voice a garbage syllable into the gap (verified A/B on Wife Flooded the House L45). The completing speaker's line follows intact. Still stochastic: spot-check cut-off lines in QC. Everywhere else the no-dash law stands absolute.", get: "The interruption beat written into the script + dialogue manifest so it cuts clean on the first fire.", status: "Team", tier: "live", flow: false },
  { num: "WR 11", section: "WR", id: "wr.kitchen", folder: "wr.kitchen", forr: "The kitchen test — rewriting RETOLD DIALOGUE in a story-ad script into spoken-human register. Keeps every who-said-what tag and every fact/number; kills the book words (said-bookisms, adverbial tags, written-English constructions). Josiah Akimenko's technique, maintained by him.", when: "The editor invokes it — \"kitchen test this\", \"kitchen convo pass\", \"this dialogue sounds stiff\", \"/wr.kitchen\". Opt-in only, never auto-run by the writers.", how: "Touches only retold-dialogue lines: said-bookisms → said/goes/was like, adverbial tags dropped, formal constructions → spoken register, long perfect-recall quotes compressed to the remembered punch. 🔴 Gate 0 on LC-sourced scripts: confirm with Dima first whether he is testing the verbatim LC copy or wants it naturalized — a rewrite silently invalidates a copy test. Delivers before→after pairs per changed line, then the clean script; word-count + compliance lint before ship.", get: "The same script with dialogue a real person would actually say out loud — register fixed, story/facts/tags untouched.", status: "Team", tier: "live", flow: false },
  { num: "AG 1", section: "AG", id: "ag.stage", folder: "stage-request", forr: "Making a written request FIRE-READY — the bridge between writing and generation. Team skill: any editor stages their own request, then routes it to the 24/7 office mini to generate overnight (no need to tie up their own account or stay logged in) OR fires it locally on the spot.", when: "\"/stage request\" after a request is written; anything headed to AGF must pass through here.", how: "Resolves the source creative's master prompt + refs (scene frames, never bare masters), scaffolds the full project folder on Lucid, writes the verbatim dialogue manifest + the 🤖 Asset Gen section on the request, runs a fresh-context verifier agent on its own work, then asks: send to AGF (flip Ready, mini fires it) or generate locally now.", get: "A staged request — folder + manifest + refs locked; Asset Gen property set.", status: "Team", tier: "live", flow: false },
  { num: "AG 2", section: "AG", id: "ag.hvg.flow", folder: "hvg-flow", forr: "THE main video pipeline — a project's initial Veo batch, from Notion request to delivered clips.", when: "MANDATORY for a project's first gen (skips only if you say \"one-off\"/\"quick\"/\"direct CLI\"). Refires/regens on existing projects fire direct instead. Trigger: drop the Notion URL in the project folder or say \"run HVG\".", how: "Silent setup (fetch, parse the request format, model lock Veo Lite +audio count=1 9:16, master prompt, xlsx manifest), stops at most twice (ambiguous refs + the Fire? preflight with cost). Fires via CLI, streams every clip the instant it lands (📲 + widget), downloads verified into Elements/Footage/Veo/, then OFFERS QC — never runs it on you.", get: "The full clip batch on Lucid + manifest + delivery offer (r.delivery).", status: "Team", tier: "live", flow: true },
  { num: "AG 3", section: "AG", id: "ag.hig.flow", folder: "hig-flow", forr: "The image-batch pipeline + owner of the shared firing engine (fire_batch.py) all b-roll skills use; fallback drafter for mixed batches.", when: "Rarely directly — b-roll routes type-first (AG 11-15). Use when a batch fits NO type (\"fire the mixed b-roll\") .", how: "Same gated shape as hvg: silent setup, shot-list draft from the brief, NB Pro 1k count=1 9:16 lock, one preflight, spine fire with streaming, verified download to B-Roll Photos/. Its PIPELINE-SPEC.md documents the engine contract the type skills call.", get: "The image batch on Lucid + manifest.", status: "Team", tier: "live", flow: true },
  { num: "AG 4", section: "AG", id: "agf", folder: "agf", forr: "The autonomous generation robot — fires staged requests on the office Mac mini with nobody watching.", when: "You never run it; the scheduler does. You feed it by staging requests → Ready.", how: "Scans the VTM for Asset Gen = Ready, claims one at a time (→ Generating), smoke-fires, then the full batch in waves, mandatory audio QC (the sanctioned exception — nobody's watching), refires flagged clips, delivers to the folder + Notion comment + Slack, flips Delivered/Failed with the reason. Watcher v3.6+ alarms on stalls.", get: "Delivered clip batches + Notion/Slack notifications, hands-off.", status: "Sam/mini ONLY", tier: "restricted", flow: false },
  { num: "AG 5", section: "AG", id: "ag.image.oneoff", folder: "higgsfield-image-generation", forr: "Quick one-off images — single shots, character variations, prompt tests — without the batch pipeline.", when: "\"Generate this image\" / \"a few variations of X\" / testing a look before committing to a batch.", how: "Loads ag.prompt.nb for the prompt body (mandatory), fires via CLI (NB Pro 1k count=1 9:16 default), shows each result the moment it exists (📲 + widget), downloads with hex-tagged filenames so nothing overwrites. Misses are named and shown — you call refires. 5+ images → routes to the spine instead.", get: "Downloaded image(s) in the project folder + tappable links.", status: "Team", tier: "live", flow: false },
  { num: "AG 6", section: "AG", id: "ag.generate", folder: "higgsfield-generate", forr: "Vendor catch-all generator (any model) + Marketing Studio. Fenced away from PFM work.", when: "Non-PFM experiments and Marketing Studio only. PFM one-offs route to ag.image.oneoff.", how: "Vendor-maintained; carries a PFM header enforcing our defaults (9:16, cheap rungs, handoff links) if it ever runs on PFM work.", get: "Whatever the vendor flow produces.", status: "Vendor (fenced)", tier: "vendor", flow: false },
  { num: "AG 7", section: "AG", id: "ag.prompt.nb", folder: "nano-banana-prompting", forr: "The prompt-craft bible for our image model — the difference between AI-stock-photo and shot-on-a-phone-real.", when: "Loads automatically under every PFM image fire; or ask directly for prompts in one of its three modes.", how: "Router picks the mode: structured layered prompts (social-proof/character scenes), broadcast-news look (ENG camera, lavaliers), or iPhone camera-roll (minimal ~700-char, anti-glossy). Each mode's full template + tells/antidotes lives in its reference file. House default 9:16.", get: "The prompt body the firing skill uses.", status: "Team", tier: "live", flow: false },
  { num: "AG 8", section: "AG", id: "ag.char.master", folder: "pfm-character-master", forr: "Creating a character's master sheet — the 5-angle scale-anchored identity reference every future gen of that character builds from.", when: "Any new recurring character. Mode A: describe them in words. Mode B: hand me a real photo (\"turn this into a master\").", how: "Builds the locked-format sheet (5 angles + a face-portrait close-up + 5'10\" silhouette anchor, style per character) on gpt_image_2, one take default. You approve → it AUTO-SAVES to the Character Library + Prompts sheet (no ask) and announces the save. Format details live in references/master-format.md.", get: "The approved master in the Character Library — the identity source for all downstream gens.", status: "Team", tier: "live", flow: false },
  { num: "AG 9", section: "AG", id: "ag.char.place", folder: "character-studio", forr: "Placing a finished master into a locked PFM environment (podcast set, talk-show couch, news interview, keynote stage) as a scene still.", when: "\"Put <character> on a podcast / on stage / in a news interview.\" NOT for the existing JRE frame — that's ag.broll.jre.", how: "Master goes in as the single identity ref; the scene comes from the locked archetype prose; aspect follows the TARGET scene (16:9 for podcast/news/keynote, 9:16 for vertical) — not a fixed default. One gen, shown instantly; the still becomes the Veo seed frame.", get: "The placement still in Reference/ — feeds video generation.", status: "Hold (Sam-local)", tier: "hold", flow: false },
  { num: "AG 10", section: "AG", id: "ag.char.board", folder: "character-board", forr: "Keeping the browsable tile index of the whole AI cast current.", when: "After new masters land: \"refresh the character board\".", how: "build_board.py re-renders the flat tile page from the Character Library. Idempotent — safe anytime.", get: "The updated board + link.", status: "Team", tier: "live", flow: false },
  { num: "AG 11", section: "AG", id: "ag.broll.iphone", folder: "iphone-broll", forr: "The camera-roll photo sets that cut between podcast talking beats — built fresh from a script, or rebuilt wholesale around a NEW character.", when: "\"Make iphone b-roll for this script\" (fresh) / \"same b-roll but with <character>\" (identity swap).", how: "Never uses original b-roll as refs (that's how identity bleeds) — drives every shot from locked masters + locked empty-environment plates + fresh prose. Gated shot list → spine fire (streams each shot) → misses named and shown, you call regens. Phone-with-quote beats delegate to AG 13.", get: "The photo set in Primary/B-Roll Photos/, 2 options per dialogue line typical.", status: "Team", tier: "live", flow: false },
  { num: "AG 12", section: "AG", id: "ag.broll.jre", folder: "jre-swap", forr: "Putting a new character onto the existing JRE podcast frame (red curtain, SM7B mic) with the set pixel-identical to previous creatives.", when: "\"Put <character> on the JRE pod\" / staging a character variation of an existing podcast creative.", how: "Recreation-swap: the locked scene frame goes in as the template ref + the new character's identity refs; the model recreates the exact frame with only the person changed. One take default; four-lock checklist (set/framing/solo/identity) shown with the result.", get: "The swapped podcast still — the new character's scene seed.", status: "Team", tier: "live", flow: false },
  { num: "AG 13", section: "AG", id: "ag.broll.socialproof", folder: "social-proof-phone-quote", forr: "The held-phone-with-the-quote-on-screen social-proof shot that has to read real.", when: "\"Social proof\" / \"holding their new rate\" — any brand, generic customers or a specific story character.", how: "The quote-page graphic (gpt_image_2-built, text-perfect) goes in as reference 1; the whole scene generates AROUND it in one NB Pro pass — never composited after (always reads pasted). Screen sharpness + face hold checked, shown instantly.", get: "The social-proof still(s) in the project folder.", status: "Team", tier: "live", flow: false },
  { num: "AG 14", section: "AG", id: "ag.broll.news", folder: "broadcast-news-stills", forr: "News-look stills — anchors, field standups, sit-down interviews — that read as broadcast freeze-frames, not photo shoots.", when: "B-roll for any breaking-news creative: \"news stills\" / \"anchor shot\" / \"field reporter\".", how: "Owns the news-look craft (scene-not-frozen framing, ENG camera declaration, lavalier mics) and defers prompt bodies to ag.prompt.nb broadcast mode; fires through the spine, streams results, editor calls refires.", get: "News stills in the project's Reference/B-Roll folders.", status: "Team", tier: "live", flow: false },
  { num: "AG 15", section: "AG", id: "ag.broll.objects", folder: "object-inserts", forr: "The no-people cutaways — bill on the counter, keys, mailbox, hands on the wheel — that give story ads texture.", when: "\"Object shots\" / \"insert of the bill\" / \"no-people b-roll\".", how: "No character needed. Lived-in anti-stock craft (worn not glossy, correct grain, aged-bill cues, no phone UI chrome); spine fire, streamed, editor-called regens.", get: "The insert set in B-Roll Photos/.", status: "Team", tier: "live", flow: false },
  { num: "AG 16", section: "AG", id: "ag.ugc.ref", folder: "ugc-talking-head-ref", forr: "The hero still for a UGC-style presenter — the paused-mid-sentence phone-video look.", when: "Starting any UGC creative: new presenter (\"finance bro\", \"car-seat mom\") or swapping one.", how: "Locked look (mid-speech frame, tight framing, clean iPhone, NOT a posed portrait) on NB Pro / Z Image podcast mode. Every take shown the instant it lands; contact strip + verdicts after; you pick the hero.", get: "The presenter reference still that AG 17 consumes.", status: "Team", tier: "live", flow: false },
  { num: "AG 17", section: "AG", id: "ag.ugc.veo", folder: "ugc-talking-head-veo", forr: "The locked Veo prompt package that turns a UGC still into talking clips.", when: "Right after AG 16, or when UGC dialogue changes.", how: "Writes the six-block prose master + verbatim dialogue manifest (word windows, no leading silence); refuses to fire — hands the package to hvg-flow/AGF, keeping write and fire separated.", get: "Master prompt + manifest, stage-ready.", status: "Team", tier: "live", flow: false },
  { num: "AG 18", section: "AG", id: "ag.ugc.cinematic", folder: "ugc-cinematic-prompt", forr: "Prompt writing for Seedance/Kling (the OTHER video models) in the strict 11-block format.", when: "\"Seedance prompt\" / Kling work / the prompt engine inside reskins and no-cuts interviews. Never for Veo.", how: "Builds STYLE→TIMESTAMPS block prompts adapted to any aesthetic; carries the PFM compliance overlay; optional CLI fire tail (count=1).", get: "The prompt (and optionally the fired clip).", status: "Team", tier: "live", flow: false },
  { num: "AG 19", section: "AG", id: "ag.pod.guest", folder: "podcast-guest-veo", forr: "The locked voice/audio treatment keeping a podcast guest's voice consistent across every clip.", when: "New podcast guest, or \"the audio sounds off on the podcast clips\" (repair).", how: "Writes/repairs the master's audio blocks (clarity stack, negative walls, no-cinematic law) with A/B test discipline — fires a 2-3 clip test, you listen, you call the full run.", get: "The repaired/locked master prompt.", status: "Team", tier: "live", flow: false },
  { num: "AG 20", section: "AG", id: "ag.life", folder: "veo-life", forr: "Bringing finished stills to life as 6s locked-camera cinemagraphs (breathing, blinks, one atmospheric motion, no audio).", when: "\"Bring these to life\" / blue-tag stills in Finder / motion versions of a social-proof batch.", how: "Intake (blue-tag scan / files / folder) → per-still prompt from the locked cinemagraph template → gated preflight → detached fire streaming each clip as it lands → OFFERS filmstrip QC (delegates to qc.video).", get: "6s clips beside their source stills + manifest.", status: "Team", tier: "live", flow: false },
  { num: "AG 21", section: "AG", id: "ag.voice.swap", folder: "labs-voice-swap", forr: "Re-voicing generated clips with a chosen ElevenLabs voice while lip-sync holds (speech-to-speech keeps timing).", when: "Every Max the Dog creative; any \"swap/fix the voice on these clips\".", how: "voice_swap.py runs STS per clip with a duration-drift guard (DURDRIFT check); proves ONE clip first (before/after shown 📲 + widget), you approve, then the batch. Never overwrites originals.", get: "Re-voiced copies beside the originals.", status: "Team", tier: "live", flow: false },
  { num: "AG 22", section: "AG", id: "—", folder: "higgsfield-soul-id", forr: "(retired)", when: "—", how: "Archived 07-09 — identity training path our master-sheet system replaced.", get: "—", status: "RETIRED", tier: "retired", flow: false },
  { num: "AG 23", section: "AG", id: "ag.ecom.photoshoot", folder: "higgsfield-product-photoshoot", forr: "Vendor product-photography generator.", when: "Non-PFM product/brand work only.", how: "Vendor-owned interview + backend prompts on gpt_image_2.", get: "Product imagery.", status: "Vendor (fenced)", tier: "vendor", flow: false },
  { num: "AG 24", section: "AG", id: "ag.ecom.cards", folder: "higgsfield-marketplace-cards", forr: "Vendor marketplace-listing image generator.", when: "Non-PFM listings only.", how: "Vendor-owned; backend compliance templates.", get: "Listing image sets.", status: "Vendor (fenced)", tier: "vendor", flow: false },
  { num: "AG 25", section: "AG", id: "ag.rctv.c.bn.flow", folder: "assetgen-rokuctv-calls-breakingnews", forr: "The complete asset factory for a Roku CTV Breaking News variant — one job, editor never chases steps.", when: "A BN city/state/number-set request lands: \"/ag.rctv.c.bn\" or \"run the BN pipeline\".", how: "Reuse-first staging → Rachel standups (\"Yeah,\" lead) → banner/endcard via ag.graphics.call → CALL NOW chyrons + CITY headlines → Steve wall composites via ag.bn.wall → BOTH close halves (L11a+L11b w/ clarity block) → city-named files → digit-verify → additive DaVinci import → delivery. Handles pending-number requests via the TBD fork.", get: "The full BN asset kit, imported and delivered.", status: "Team", tier: "live", flow: true },
  { num: "AG 27", section: "AG", id: "ag.rctv.c.qvc.flow", folder: "assetgen-rokuctv-calls-qvc", forr: "The complete asset factory for the SaveMaxAuto Live shopping-channel creative.", when: "A QVC Live request (new city/state/numbers): \"/ag.rctv.c.qvc\".", how: "Cast+set lock (first build) → host clips off approved scene frames → ElevenLabs caller VOs → graphics package via ag.qvc.screens + ag.graphics.call → digit-verify → additive DaVinci import → delivery. Spoken-rate compliance check offered pre-delivery.", get: "The full QVC asset kit.", status: "Team", tier: "live", flow: true },
  { num: "AG 29", section: "AG", id: "—", folder: "ctv-bn-variation", forr: "(retired stub)", when: "You don't — redirects to AG 25.", how: "3-line stub; unique pieces were ported into AG 25.", get: "—", status: "RETIRED (stub)", tier: "retired", flow: false },
  { num: "AG 30", section: "AG", id: "ag.vsl.states.flow", folder: "vsl-state-variations", forr: "Per-state variants of a winning VSL (the Chad keynote family) — slides AND clips in one run.", when: "A \"VSL - ... State Cost Pitch <State>\" request beside the shared VSL project.", how: "Phase 1: edit-swap the state's slide images off the locked base set. Phase 2: Veo Lite clips per script line (Fire? card, streamed, NSFW recovery ladder). QC offered after delivery, spoken-rate check recommended.", get: "State slides + clips in the shared project, per the locked templates.", status: "Team", tier: "live", flow: true },
  { num: "AG 31", section: "AG", id: "ag.anim.pixar.flow", folder: "pixar-state-music-video", forr: "Per-state animated music-video assets: the state-outline mascot + 12 scenes + song prep.", when: "A \"50 States - <style> Average State - <State>\" request: \"do the <state> pixar video\".", how: "Fires the character master + 12 locked-structure scene frames (NB Pro, state-derived tokens), preps state-filled lyrics + Suno style block. YOU run Suno; Mark assembles. Streams stills as they land.", get: "Character + 12 scenes + Suno-ready lyric kit.", status: "Team", tier: "live", flow: true },
  { num: "AG 32", section: "AG", id: "ag.graphics.call", folder: "call-graphics", forr: "Phone-number graphics for Calls creatives: the persistent banner + full-screen end card, digit-perfect.", when: "\"Make the call graphics / banner and end card\" — any brand with a template library (SMA, SMH).", how: "Resolves the brand's design.md templates on Lucid, asks which design, fires gpt_image_2 2k with the real tracking numbers, digit-verifies every output by reading it back, shows each as it lands, delivers with full links. Banner defaults to the taller ~1/5 band so the compliance/disclaimer line always fits.", get: "Banner + EndCard PNGs in the project folder, verified.", status: "Team", tier: "live", flow: false },
  { num: "AG 33", section: "AG", id: "ag.bn.thirds", folder: "bn-lower-thirds", forr: "The breaking-news lower-third strips (state headline + CALL NOW).", when: "⚠️ DON'T right now — frozen since PFM exited Canva; rebuild on the HTML render method pending.", how: "Was: Canva template deck text-swaps → transparent PNG export. Page maps preserved in references/ for the rebuild.", get: "(when rebuilt) Transparent strip PNGs in Elements/Graphics/<State>/.", status: "🔴 FROZEN", tier: "frozen", flow: false },
  { num: "AG 34", section: "AG", id: "ag.bn.wall", folder: "anchor-wall-composite", forr: "Compositing the verified EndCard onto Steve's studio video wall — the reference frame for BN close-line clips.", when: "After ag.graphics.call delivers, on BN creatives only: \"steve wall\" / \"anchor wall\".", how: "One gpt_image_2 composite fire with the locked inline prompt; Read-verifies digits on the wall; refire caps + ask-before-deviating. Never used on non-BN sets (locked after the podcast-screen incident).", get: "The D-locked wall reference frame for the close cinemagraphs.", status: "Team", tier: "live", flow: false },
  { num: "AG 35", section: "AG", id: "ag.reskin.flow", folder: "reskin-trending-video", forr: "Recreating a trending clip brand-safe with our character swapped in.", when: "\"Reskin this\" / \"do this trend with Max\" + a reference clip.", how: "inspect_video.sh breaks down the reference → intent check → engine pick (Seedance vs Kling motion-control) → prompt via ag.ugc.cinematic → IP/brand-safety catch (watermarks, plates, alcohol) → optional fire.", get: "The reskin prompt (and optionally the clip).", status: "Team", tier: "live", flow: true },
  { num: "AG 36", section: "AG", id: "ag.qvc.screens", folder: "qvc-screen-graphics", forr: "The QVC overlay package: ticking savings board, checklist, caller counter, deal card, lower-thirds, channel bug.", when: "\"Board graphics\" / a QVC city variant needs its overlays.", how: "v3 method: HTML/CSS templates rendered by headless Chrome → exact digits, native alpha, zero credits; states are template params on ONE approved layout; PIL keyframe engine renders animated alpha MOVs (ticks, check pops). Alpha audit + digit-verify built in.", get: "PNG states + ProRes-alpha MOVs per element.", status: "Team", tier: "live", flow: false },
  { num: "AG 37", section: "AG", id: "ag.ugc.interview.flow", folder: "ugc-interview-flow", forr: "UGC group interviews, TWO MODES — Mode A NO-CUTS one-take (chained clips that butt-join seamlessly; open settings) and Mode B CUTS (location masters + distinct cast cards → independent per-station clips; multi-room/store locations where a one-take breaks). Zach Hustead's method, maintained by him — proven on four full 8-way matrices.", when: "\"No cuts\" / \"one-take\" (Mode A) · \"cuts version\" / \"like Home Depot / Cleaners\" (Mode B) · any \"UGC Interview - <Setting> Crew/Party/Meet\" request. Mode picked by LOCATION, confirmed with you.", how: "Script is LAW in both modes (verbatim, demographic adaptations only). Mode A: editor-stamped wide → each clip seeded from the previous approved clip's real last frame → pixel-gated auto-refires on seam mismatch → you stamp every clip; editor stitches (I never concat). Mode B: 3 gated waves — brandless location masters (serial text fires) → distinct-identity cast cards (branding audit + surgical wipes) → independent Seedance clips per station (15s hard cap, CTA lander via --medias, locked anti-radio/chant-guard/screen-orientation prompt stack). Both playbooks in references/.", get: "Approved clips per demographic version — chains (A) or per-station cuts (B); no stitch files ever.", status: "Team", tier: "live", flow: true },
  { num: "AG 38", section: "AG", id: "ag.broll.mascot", folder: "pixar-mascot-broll", forr: "Pixar vignettes of the brand mascot acting out script lines — VSL cutaway b-roll.", when: "\"Make pixar b-roll\" for a VSL with a canon mascot (Max).", how: "Select ~half the lines (concrete beats only) → grounded slice-of-life concepts (never abstract metaphor) → TABLE sign-off → ⭐7 test batch → full fire on gpt_image_2 2k with canon + model-sheet refs → Kling i2v handoff.", get: "L-numbered scene PNGs in <Mascot> B-Roll Scenes/, Kling-ready.", status: "Team", tier: "live", flow: false },
  { num: "AG 39", section: "AG", id: "ag.loc.360", folder: "environment-location-builder", forr: "360° location sheets for spatially-consistent AI locations — from a location brief to a hero photo prompt, then a 2×2 front/back/left/right sheet from the same camera spot, so flips, pans, and POV changes match across generated shots. Drake's technique, maintained by him.", when: "You want to create a place/environment/scene for AI gen, have one location photo and need the surrounding views, or your camera flips keep breaking the location — \"create a location\", \"location sheet\", \"360 view of a place\", \"/ag.loc.360\".", how: "Prompts only — it never generates images. Step 1 captures the brief (one round of questions max). Step 2 delivers the max-quality hero photo prompt (eye-level 0° anchor, shadow-casting realism). Step 3-4 hand you the bundled 2×2 layout template + the sheet prompt with anti-re-centering constraints (side panels show the hero subject only as an edge sliver) and world-consistent lighting. NB Pro recommended — it handles the 360° spatial inference best.", get: "Two copy-paste prompts + the layout template → one coherent 360° space to reference for every shot at that location.", status: "Team", tier: "live", flow: true },
  { num: "QC A", section: "QC", id: "qc.audio", folder: "audio-qc", forr: "Catching audio defects in generated batches: silence, clipping, wrong dialogue, rogue music.", when: "OFFERED after any batch (your call, never auto on local fires; mandatory only inside AGF). \"QC the clips.\"", how: "Three phases: ffmpeg physics (~90s per 350 clips) → Whisper transcription fuzzy-matched against the manifest → music detection piggybacked on both. Note: spoken numbers transcribe as digits, so number lines verify by ear, not score.", get: "Flag report per clip with recovery recommendations — refires are your call.", status: "Team", tier: "live", flow: false },
  { num: "QC V", section: "QC", id: "qc.video", folder: "visual-qc", forr: "Catching what audio can't: face morphs, garbled slide text, hallucinated overlays, hard cuts.", when: "Offered after batches — strongest on VSL/slide work with fine on-screen text.", how: "5-frame filmstrip per clip (+ full-res end frames for caption slides), I read each strip and call ✓/✗/verify. The single filmstrip owner — other skills delegate here.", get: "Per-clip verdict report; you decide regens.", status: "Team", tier: "live", flow: false },
  { num: "QC G", section: "QC", id: "qc.gemini", folder: "watch-video", forr: "Watching a generated clip with human-level eyes via Gemini — the deep QC for when audio + filmstrip aren't enough.", when: "On-demand when a clip needs a real watch, or as QC escalation. Optional Tier-2 — never blanket.", how: "Sends the clip to Gemini to actually WATCH it and report what happens on screen + in the audio; plain-language verdict per clip.", get: "A watched-it verdict (what's really in the clip), beyond audio-QC + the filmstrip.", status: "Team", tier: "live", flow: false },
  { num: "E 1", section: "E", id: "e.davinci.flow", folder: "claude-editor", forr: "The DaVinci assembler: batch → imported → rough-cut stringout, purely additively, in YOUR open project.", when: "\"Assemble this in DaVinci\" / \"build the <state> stringout\" on podcast creatives.", how: "Phase 1 import (whole-folder mirror, ALL dirs even empty, never deletes); Phase 2 assemble (manifest-ordered 9x16 stringout, name-confirm); Phase 3/4 defer to /e.propagate + /e.export. SMA disclaimer checked at assemble AND export. Single source for timeline naming.", get: "The stringout timeline ready for your manual pass.", status: "Hold (Sam-local)", tier: "hold", flow: false },
  { num: "E 2", section: "E", id: "e.palmier.pod.flow", folder: "lctovid-podcast-palmier", forr: "Assembling podcast creatives in Palmier (the AI editor under evaluation) — rebuilds, state swaps, cross-state replications.", when: "\"Assemble/build in Palmier\" during the eval.", how: "Four modes vs a DaVinci reference or bare script; drives Palmier's MCP (PiP, b-roll, speed, captions); machine-diff verify + black-gap battery + transcript QC; FLAT pipeline law (pre-speed media, build at 1.0).", get: "The Palmier timeline(s), verified, ready to export back to DaVinci.", status: "Hold (eval)", tier: "hold", flow: false },
  { num: "E 3", section: "E", id: "e.import.palmier", folder: "palmier-davinci-import", forr: "The bridge back: Palmier FCPXML exports landing in DaVinci with zero offline media.", when: "After a Palmier export: \"import the timelines into DaVinci\".", how: "GUI import for a few timelines (bulletproof) or the hardened API script for state fan-outs; verifies every clip linked (0 unlinked = the named check); asks YOU to delete any failed prior attempts.", get: "Linked timelines in your open project.", status: "Hold (eval)", tier: "hold", flow: false },
  { num: "E 4", section: "E", id: "e.disclaimer", folder: "add-ai-disclaimer", forr: "Burning the legally-required AI-performer disclaimer onto FINISHED videos (SMA compliance).", when: "\"Add the disclaimer\" / an SMA re-export request with finished cuts.", how: "Auto-detects aspect per file → locked 06-12 preset (9:16 bold italic 2 lines low; 16:9 one line bottom strip; ~92% white italic full duration) → clean H.264 re-encode, audio untouched, source never modified. Batch or single.", get: "Disclaimer'd copies beside the originals.", status: "Team", tier: "live", flow: false },
  { num: "R 1", section: "R", id: "r.delivery", folder: "notion-asset-delivery", forr: "Posting the official delivery comment on the request — the house-format handoff.", when: "\"Deliver this to Notion\" / auto-offered by the gen flows / the engine behind /r.assets + /r.creative.", how: "Builds the LinkYourFile link, composes ① ✅ Assets Generated (status untouched) or ② ✅ Completed Creatives (N) (status→Done + @Dima V @Gabriel Moss), POSTS IMMEDIATELY when you asked — flag-mode preflight only when something's off (count mismatch, unverified disclaimer).", get: "The posted comment + status/tags per path.", status: "Team", tier: "live", flow: false },
  { num: "X 1", section: "X", id: "x.propose", folder: "propose-skill", forr: "Turning an editor's repeatable workflow into a proposal Sam can build into a team skill.", when: "\"This should be a skill\" / \"I keep doing this\". Editor-facing.", how: "Reconstructs the workflow from the session (or interviews), asks targeted gap questions, writes the structured proposal to the Lucid inbox with 📁+🔗 links. Zach's no-cuts skill came through this pipe.", get: "The proposal file in Skill Proposals/, awaiting triage.", status: "Team", tier: "live", flow: false },
  { num: "X 2", section: "X", id: "x.find", folder: "find-skills", forr: "Searching the public registry for external skills — tightly fenced.", when: "Only an explicit \"find an external skill for X\". Never generic how-do-I questions.", how: "Searches skills.sh; PFM-internal always precedes; editors propose, never install (installs are Sam's call).", get: "Candidates + a recommendation.", status: "Sam-gated", tier: "restricted", flow: false },
  { num: "X 3", section: "X", id: "x.sync", folder: "x.sync", forr: "The distribution system — keeps Lucid/hub/plugin honestly in sync with the source of truth.", when: "\"/x.sync\" anytime (free report); \"push it\" after skill work that should reach editors.", how: "Report mode: checksum-diffs all 55 manifest entries vs Lucid + hub catalog + context staleness, read-only. Push mode: NAMED list → your approval → rsync → re-checksum every dir (VERIFIED n/n or NOT VERIFIED). The manifest (team/hold/never/vendor) is the single authority on what ships.", get: "The drift report / the verified push.", status: "Sam-only", tier: "restricted", flow: false },
  { num: "X 6", section: "X", id: "pfm-naming", folder: "pfm-naming", forr: "THE single source for PFM naming — the locked convention for request titles, project folders, DaVinci timelines, and creative/export filenames.", when: "\"What do I name this timeline / export / folder?\" / \"is this named right?\" — or any skill creating/renaming one of those surfaces.", how: "Carries the four locked renderings (Sam 2026-07-14): request title = display name (no Vertical/Lead); folder = MM.DD.YY + display name; timeline/creative/export = Vertical - Lead - [Platform] - VARIABLE - Creative Type - Concept - [tail] - MM.DD.YY, where VARIABLE is the per-timeline state or text hook (H1/H2/H3). Plus the display-name vs Full-Name distinction and the strip-the-Video(s)-tail rule, with worked examples.", get: "The correct name for any PFM surface, consistently.", status: "Team", tier: "live", flow: false },
  { num: "E 5", section: "E", id: "/e.assemble", folder: "e.assemble.md", forr: "Builds the stringout timeline from an imported batch (claude-editor Phase 2).", when: "When you're ready to build: /e.assemble.", how: "Asks deliverable format + confirms the timeline name (naming from claude-editor), runs the assemble script.", get: "The named stringout in Creatives/<batch>.", status: "Command", tier: "command", flow: false },
  { num: "E 6", section: "E", id: "/e.propagate", folder: "e.propagate.md", forr: "Duplicates your edited master across the batch's other states, edit work intact.", when: "After the master edit is locked: /e.propagate.", how: "Imports target states' clips, DuplicateTimeline per state, swaps the Variation name segment, offers Zach's swap-assist (silence-detect pre-marks, orange worklist, chunked attribute paste). Named check: created/requested timelines.", get: "Per-state duplicates ready for clip swaps.", status: "Command", tier: "command", flow: false },
  { num: "E 7", section: "E", id: "/e.export", folder: "e.export.md", forr: "Batch-renders finished timelines with the saved preset.", when: "/e.export (add 'start' to render now).", how: "Queues every Creatives/<batch> timeline (CLAUDE EDITOR EXPORT preset: 4000 kb/s, burned subs, marks=range, filename=timeline name), ffprobe-verifies each render, full 📁🔗🦊 handoff, then offers /r.creative.", get: "Verified MP4s in the Creatives folder.", status: "Command", tier: "command", flow: false },
  { num: "E 8", section: "E", id: "/e.subs", folder: "e.subs.md", forr: "Auto-captions named timelines in DaVinci.", when: "Only when YOU ask: /e.subs <substring> (--redo replaces).", how: "Runs dv_subs.py per matching timeline; per-timeline OK/FAIL + item count.", get: "Captioned timelines.", status: "Command", tier: "command", flow: false },
  { num: "E 9", section: "E", id: "e.timeline", folder: "e.timeline", forr: "The timeline handoff system — publishes DaVinci timelines as .drt files into the project's Creatives/Timelines/ so the next editor picks a project up without hunting timelines or relinking media.", when: "\"Hand off this project\" / \"pick up <project>\" / \"import <editor>'s timeline\" / \"grab the timeline for batch 2\".", how: "Export leg: .drt named exactly like the creative (one timeline per creative), versions up never overwrites, and flags any clip path outside Lucid at publish time — the #1 cause of offline media, caught before the handoff. Import leg: into YOUR OWN open project (never someone else's), auto-mirrors the project folder into bins first, places the timeline at its Finder-matched bin path (Creatives/Parent Timelines), then verifies every referenced file on disk. Parent media stays referenced in place — never copied.", get: "The timeline online in your own project, media linked, ready to cut the next batch.", status: "Team", tier: "live", flow: false },
  { num: "E 10", section: "E", id: "e.timeline.export", folder: "e.timeline.export", forr: "Standalone timeline publish — the .drt export WITHOUT a render, for projects you rendered manually outside /e.export.", when: "\"Export the timelines\" / \"publish the timelines\" after a manual render — or say yes when the turn-in pings you.", how: "Runs e.timeline's export leg only: one .drt per creative into Creatives/Timelines/, off-Lucid path check, verified on disk.", get: "Published timelines, handoff-ready.", status: "Team", tier: "live", flow: false },
  { num: "R 2a", section: "R", id: "/r.assets", folder: "r.assets.md", forr: "Posts the raw-asset handoff comment.", when: "/r.assets when generated assets are ready.", how: "Delegates to r.delivery path ① — status untouched, no count, posts immediately.", get: "The ✅ Assets Generated comment.", status: "Command", tier: "command", flow: false },
  { num: "R 2b", section: "R", id: "/r.creative", folder: "r.creative.md", forr: "Posts the completed-creative turn-in.", when: "/r.creative when the export is done.", how: "SMA-disclaimer verify → r.delivery path ② — Status→Done, @Dima V + @Gabriel Moss, count, posts immediately. Then checks Creatives/Timelines/ and pings you to publish any missing timelines (/e.timeline.export).", get: "The ✅ Completed Creatives (N) comment.", status: "Command", tier: "command", flow: false },
  { num: "X 4", section: "X", id: "/x.notion", folder: "x.notion.md", forr: "Re-reads the session's Notion request and reports what changed.", when: "/x.notion mid-project.", how: "Read-only refetch + diff-style report; never edits, never re-asks the URL.", get: "The what-changed report.", status: "Command", tier: "command", flow: false },
  { num: "X 5", section: "X", id: "/x.view", folder: "x.view.md", forr: "Public phone-viewable link for any local asset.", when: "/x.view away from the desk.", how: "higgsfield upload → 📲 CloudFront link (+ widget for fresh gens); never fires a gen.", get: "The tappable link.", status: "Command", tier: "command", flow: false },
];

/** Skills intentionally bundled for hosted Cowork/chat use. */
export const coworkSkillFolders = [
  "stage-request",
  "veo-script-writing",
  "breaking-news-story-ads",
  "nano-banana-prompting",
  "story-beats",
  "lc-to-video-podcast",
  "suno-songwriter",
  "human-ad-copy",
] as const;

export const coworkSkillFolderSet = new Set<string>(coworkSkillFolders);

/** Team-distributed skills. Every one must have public/skills/<folder>/SKILL.md. */
export const distributedSkillRows = skillRows.filter((skill) => skill.tier === "live");

/** Strip trigger annotations from the registry's human-readable folder field. */
export function skillFolder(skill: SkillRow): string {
  return skill.folder.split(" · trigger ")[0].replace(/\.md$/, "");
}

export function skillTitle(skill: SkillRow): string {
  return skillFolder(skill)
    .split("-")
    .map((word) => word.length <= 3 ? word.toUpperCase() : word[0].toUpperCase() + word.slice(1))
    .join(" ");
}
